variables:
  STACK_FILE: '/home/ec2-user/skilling-pathway/docker-compose.yml'
  CODE_DIR: '/home/ec2-user/skilling-pathway/app/code'

before_script:
  - echo "Runner started"

stages:
  - Test
  - devBuild
  - devDeploy

Sonarqube-Check:
  variables:
    GIT_DEPTH: 0
  stage: Test
  script: 
    - docker run --rm  --volume "$PWD:/usr/src" sonarsource/sonar-scanner-cli sonar-scanner -Dsonar.projectKey=$SONAR_TOKEN  -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -D sonar.projectName=$CI_PROJECT_NAME -Dsonar.qualitygate.wait=true -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.language=py
    - sudo rm -rf ./.scannerwork
  after_script:
    - sudo rm -rf ./.scannerwork
  allow_failure: true
  only:
    - dev
  tags:
   - samhita-sonarqube


devBuild:
  stage: devBuild
  variables:
    CI_COMMIT_REF_NAME: dev
  script:
    - echo "Deploying in https://samhita-skilling-pathway.pacewisdom.in"
    - sudo rsync -ravz --exclude '.git/' ./ $CODE_DIR/ --delete
   # - sudo cp -R ./ $CODE_DIR
    - docker compose -f $STACK_FILE build
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://samhita-skilling-pathway.pacewisdom.in
  only:
    - dev
  tags:
    - samhita-dev-shared-runner
  allow_failure: false


devDeploy:
  stage: devDeploy
  variables:
    CI_COMMIT_REF_NAME: dev
  script:
    - echo "Deployment started..."
    - docker compose -f $STACK_FILE up -d
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://samhita-skilling-pathway.pacewisdom.in
  only:
    - dev
  tags:
    - samhita-dev-shared-runner
  allow_failure: false
