variables:
  STACK_FILE: '/home/ec2-user/skilling-pathway/docker-compose.yml'
  CODE_DIR: '/home/ec2-user/skilling-pathway/app/code'

before_script:
  - echo "Runner started"

stages:
  - devBuild
  - devDeploy


devBuild:
  stage: devBuild
  variables:
    CI_COMMIT_REF_NAME: dev
  script:
    - echo "Deploying in https://samhita-skilling-pathway.pacewisdom.in"
   # - sudo rsync -ravz --exclude '.git/' ./ $CODE_DIR/ --delete
    - sudo cp -R ./ $CODE_DIR
    - docker compose -f $STACK_FILE build
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://samhita-skilling-pathway.pacewisdom.in
  only:
    - dev
  tags:
    - samhita-skilling-pathway-runner
  allow_failure: false


devDeploy:
  stage: devDeploy
  variables:
    CI_COMMIT_REF_NAME: dev
  script:
    - echo "Deployment started..."
    - docker compose -f $STACK_FILE up -d
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://samhita-skilling-pathway.pacewisdom.in
  only:
    - dev
  tags:
    - samhita-skilling-pathway-runner
  allow_failure: false
