"""empty message

Revision ID: 07f1eaa78c17
Revises: 68a5241007f1
Create Date: 2023-06-01 09:47:11.899841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f1eaa78c17'
down_revision = '68a5241007f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'store', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_column('store', 'created_by')
    # ### end Alembic commands ###
