"""empty message

Revision ID: 14208414a2ca
Revises: ac7a1d4a0801
Create Date: 2023-04-04 10:45:41.762827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14208414a2ca'
down_revision = 'ac7a1d4a0801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant_profile', 'english_speaking_level',
               existing_type=postgresql.ENUM('BASIC', 'INTERMEDIATE', 'FLUENT', 'NO_ENGLISH', name='englishspeakinglevel'),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('participant_profile', 'preferred_employment_type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', name='employmenttype'),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('participant_profile', 'preferred_work_place_type',
               existing_type=postgresql.ENUM('OFFICE', 'WORK_FROM_HOME', 'WORK_FROM_FIELD', name='workplacetype'),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('profile_score', 'score',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'profile_score', 'participant_profile', ['participant_profile_id'], ['id'])
    op.drop_column('profile_score', 'participant_user_id')
    op.drop_column('profile_score', 'participant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_score', sa.Column('participant_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('profile_score', sa.Column('participant_user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profile_score', type_='foreignkey')
    op.alter_column('profile_score', 'score',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('participant_profile', 'preferred_work_place_type',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ENUM('OFFICE', 'WORK_FROM_HOME', 'WORK_FROM_FIELD', name='workplacetype'),
               existing_nullable=True)
    op.alter_column('participant_profile', 'preferred_employment_type',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', name='employmenttype'),
               existing_nullable=True)
    op.alter_column('participant_profile', 'english_speaking_level',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ENUM('BASIC', 'INTERMEDIATE', 'FLUENT', 'NO_ENGLISH', name='englishspeakinglevel'),
               existing_nullable=True)
    # ### end Alembic commands ###
