"""empty message

Revision ID: 1783cb527856
Revises: 44daca2d6405
Create Date: 2023-04-03 18:33:20.569935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1783cb527856'
down_revision = '44daca2d6405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_module_master', sa.Column('course', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'course_module_master', 'course_master', ['course'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_module_master', type_='foreignkey')
    op.drop_column('course_module_master', 'course')
    # ### end Alembic commands ###
