"""empty message

Revision ID: 2078e9ba504c
Revises: de485c77387c
Create Date: 2023-05-18 12:43:42.686548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2078e9ba504c'
down_revision = 'de485c77387c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_profile', sa.Column('summary', sa.TEXT(), nullable=True))
    op.add_column('participant_profile', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('participant_profile', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profile_score', sa.Column('level', sa.String(length=10), nullable=True))
    op.add_column('profile_score', sa.Column('participant_id', postgresql.UUID(), nullable=True))
    op.add_column('profile_score', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profile_score', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_score', 'updated_at')
    op.drop_column('profile_score', 'created_at')
    op.drop_column('profile_score', 'participant_id')
    op.drop_column('profile_score', 'level')
    op.drop_column('participant_profile', 'updated_at')
    op.drop_column('participant_profile', 'created_at')
    op.drop_column('participant_profile', 'summary')
    # ### end Alembic commands ###
