"""empty message

Revision ID: 404a2406c9f8
Revises: eb06cd3f3d7d
Create Date: 2023-04-03 17:14:46.451821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '404a2406c9f8'
down_revision = 'eb06cd3f3d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant_profile', 'highest_education',
               existing_type=postgresql.ENUM('HIGH_SCHOOL', 'GRADUATE', 'POST_GRADUATE', 'DOCTORATE', name='highesteducation'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant_profile', 'highest_education',
               existing_type=sa.String(),
               type_=postgresql.ENUM('HIGH_SCHOOL', 'GRADUATE', 'POST_GRADUATE', 'DOCTORATE', name='highesteducation'),
               existing_nullable=True)
    # ### end Alembic commands ###
