"""empty message

Revision ID: 44daca2d6405
Revises: 404a2406c9f8
Create Date: 2023-04-03 18:11:34.784011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44daca2d6405'
down_revision = '404a2406c9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
