"""empty message

Revision ID: 470ee77dcaa2
Revises: a77007a340d6
Create Date: 2023-03-28 21:04:18.943329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '470ee77dcaa2'
down_revision = 'a77007a340d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_category',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('catogory_name', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_content_master',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content_type', sa.String(length=250), nullable=True),
    sa.Column('content_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_module_master',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('module_name', sa.String(length=250), nullable=False),
    sa.Column('module_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_master',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('desctiption', sa.TEXT(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('original_price', sa.String(length=50), nullable=True),
    sa.Column('offer_price', sa.String(length=50), nullable=True),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('partner_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('language', sa.String(length=250), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('number_of_modules', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['course_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['course_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_master')
    op.drop_table('course_module_master')
    op.drop_table('course_content_master')
    op.drop_table('course_category')
    # ### end Alembic commands ###
