"""empty message

Revision ID: 53a6a2a36205
Revises: 7528abded0fb
Create Date: 2023-04-07 17:16:46.796038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a6a2a36205'
down_revision = '7528abded0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume_builder', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('resume_builder', 'gender',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume_builder', 'gender',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('resume_builder', 'email',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
