"""empty message

Revision ID: 5558d3bd7654
Revises: ac7a1d4a0801
Create Date: 2023-04-04 09:54:17.631678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5558d3bd7654'
down_revision = 'ac7a1d4a0801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_score', 'score',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'profile_score', 'participant_profile', ['participant_profile_id'], ['id'])
    op.drop_column('profile_score', 'participant_user_id')
    op.drop_column('profile_score', 'participant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_score', sa.Column('participant_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('profile_score', sa.Column('participant_user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profile_score', type_='foreignkey')
    op.alter_column('profile_score', 'score',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
