"""empty message

Revision ID: 853feb71882d
Revises: e36affcbd507
Create Date: 2023-04-03 12:19:08.767730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '853feb71882d'
down_revision = 'e36affcbd507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_builder',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('email', sa.String(length=15), nullable=True),
    sa.Column('mobile', sa.String(length=5), nullable=True),
    sa.Column('current_address', sa.TEXT(), nullable=True),
    sa.Column('education_qualification', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('work_experience', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('certification', postgresql.ARRAY(postgresql.UUID()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'participant_profile', ['id'])
    op.create_unique_constraint(None, 'profile_score', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_score', type_='unique')
    op.drop_constraint(None, 'participant_profile', type_='unique')
    op.drop_table('resume_builder')
    # ### end Alembic commands ###
