"""empty message

Revision ID: a77007a340d6
Revises: 
Create Date: 2023-03-27 13:51:41.870022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a77007a340d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_master',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution_master')
    # ### end Alembic commands ###
