"""empty message

Revision ID: ac7a1d4a0801
Revises: 1783cb527856
Create Date: 2023-04-03 18:40:44.257250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac7a1d4a0801'
down_revision = '1783cb527856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_content_master', sa.Column('course', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'course_content_master', 'course_module_master', ['course'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_content_master', type_='foreignkey')
    op.drop_column('course_content_master', 'course')
    # ### end Alembic commands ###
