"""empty message

Revision ID: c30b47dab02b
Revises: f518add06ae2
Create Date: 2023-04-26 10:09:40.799914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30b47dab02b'
down_revision = 'f518add06ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_grant_master', sa.Column('course_name', sa.String(length=250), nullable=True))
    op.add_column('course_grant_master', sa.Column('course_actual_price', sa.String(length=25), nullable=True))
    op.add_column('course_grant_master', sa.Column('course_offer_price', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_grant_master', 'course_offer_price')
    op.drop_column('course_grant_master', 'course_actual_price')
    op.drop_column('course_grant_master', 'course_name')
    # ### end Alembic commands ###
