"""empty message

Revision ID: d3d1df47908b
Revises: c30b47dab02b
Create Date: 2023-05-09 14:39:50.482088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d1df47908b'
down_revision = 'c30b47dab02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_profile', sa.Column('resume_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_profile', 'resume_added')
    # ### end Alembic commands ###
