"""empty message

Revision ID: db454246af8b
Revises: 7528abded0fb
Create Date: 2023-04-21 08:54:11.014911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db454246af8b'
down_revision = '7528abded0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_grant_master', sa.Column('course_id', sa.Integer(), nullable=False))
    op.alter_column('course_grant_master', 'participant_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_grant_master', 'participant_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('course_grant_master', 'course_id')
    # ### end Alembic commands ###
