"""empty message

Revision ID: e1b71223b155
Revises: a5e951295fd7
Create Date: 2023-04-07 16:58:03.250275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b71223b155'
down_revision = 'a5e951295fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'participant_profile', ['id'])
    op.create_unique_constraint(None, 'profile_score', ['id'])
    op.add_column('resume_builder', sa.Column('gender', sa.String(length=5), nullable=True))
    op.alter_column('resume_builder', 'mobile',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.create_unique_constraint(None, 'resume_builder', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_builder', type_='unique')
    op.alter_column('resume_builder', 'mobile',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.drop_column('resume_builder', 'gender')
    op.drop_constraint(None, 'profile_score', type_='unique')
    op.drop_constraint(None, 'participant_profile', type_='unique')
    # ### end Alembic commands ###
