"""empty message

Revision ID: e36affcbd507
Revises: 470ee77dcaa2
Create Date: 2023-03-31 17:20:41.662158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e36affcbd507'
down_revision = '470ee77dcaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_profile',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(), nullable=True),
    sa.Column('participant_user_id', postgresql.UUID(), nullable=True),
    sa.Column('highest_education', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('english_speaking_level', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('other_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interested_course', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_course_language', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_employment_status', sa.Boolean(), nullable=True),
    sa.Column('current_employment_details', sa.TEXT(), nullable=True),
    sa.Column('employment_start_date', sa.Date(), nullable=True),
    sa.Column('employment_end_date', sa.Date(), nullable=True),
    sa.Column('preferred_job_location_state', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_job_location_city', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_employment_type', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_work_place_type', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_job_role', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('profile_score',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(), nullable=True),
    sa.Column('participant_user_id', postgresql.UUID(), nullable=True),
    sa.Column('participant_profile_id', postgresql.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_score')
    op.drop_table('participant_profile')
    # ### end Alembic commands ###
