"""empty message

Revision ID: eb06cd3f3d7d
Revises: e36affcbd507
Create Date: 2023-04-03 16:19:48.093163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb06cd3f3d7d'
down_revision = 'e36affcbd507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_grant_master',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(), nullable=True),
    sa.Column('funder_id', postgresql.UUID(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'participant_profile', ['id'])
    op.create_unique_constraint(None, 'profile_score', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_score', type_='unique')
    op.drop_constraint(None, 'participant_profile', type_='unique')
    op.drop_table('course_grant_master')
    # ### end Alembic commands ###
