"""empty message

Revision ID: f518add06ae2
Revises: db454246af8b
Create Date: 2023-04-21 16:34:01.928437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f518add06ae2'
down_revision = 'db454246af8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_profile', sa.Column('mobile', sa.String(length=15), nullable=True))
    op.add_column('participant_profile', sa.Column('email', sa.String(length=45), nullable=True))
    op.add_column('participant_profile', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('participant_profile', sa.Column('address', sa.String(), nullable=True))
    op.add_column('participant_profile', sa.Column('certificates', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('participant_profile', sa.Column('educational_qualifications', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_profile', 'educational_qualifications')
    op.drop_column('participant_profile', 'certificates')
    op.drop_column('participant_profile', 'address')
    op.drop_column('participant_profile', 'gender')
    op.drop_column('participant_profile', 'email')
    op.drop_column('participant_profile', 'mobile')
    # ### end Alembic commands ###
